/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptrinhphantan;

/**
 *
 * @author quang
 */
public class NewJFrame extends javax.swing.JFrame {
    int s1=0, s2=0, s=0;
    boolean kt1=false, kt2=false;
    
//    public class Lop1 extends Thread {
//        public void run() {
//            s1=2+3;
//            kt1=true;
//        }
//    }
//    
//    public class Lop2 extends Thread {
//        public void run() {
//            s2=4+6;
//            kt2=true;
//        }
//    }
    
    public class Lop extends Thread {
        int td;
        public Lop(int td) {
            this.td = td;
        }
        public void run() {
            if(td==1) {
                s1=2+3;
                kt1=true;
            }
            if(td==2) {
                s2=4+6;
                kt2=true;
            }
        }
    }
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Lop1 td1 = new Lop1();
//        td1.start();
//        Lop2 td2 = new Lop2();
//        td2.start();
//        
//        while(true) {
//            System.out.println("Doi.....");
//            if(kt1==true && kt2==true) {
//                System.out.println(s1+s2);
//                break;
//            }
//        }

        for(int i=1; i<=2; i++) {
            Lop td = new Lop(i);
            td.start();
        }
        
        while(true) {
            System.out.println("Doi.....");
            if(kt1==true && kt2==true) {
                System.out.println(s1+s2);
                break;
            }
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
