
import java.rmi.Naming;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class frmRutTien extends javax.swing.JFrame {

    private String SoTaiKhoan;
    /**
     * Creates new form frmRutTien
     * @param SoTaiKhoan
     */
    public frmRutTien(String SoTaiKhoan) {
        initComponents();
        this.SoTaiKhoan = SoTaiKhoan;
    }

    private frmRutTien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHaiTrieu = new javax.swing.JButton();
        btnMotTrieu = new javax.swing.JButton();
        btnNamTram = new javax.swing.JButton();
        btnHaiTram = new javax.swing.JButton();
        btnMotTram = new javax.swing.JButton();
        btnSoKhac = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle("Rút tiền");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("VUI LÒNG CHỌN SỐ TIỀN MUỐN RÚT");

        btnHaiTrieu.setText("50.000 VND");
        btnHaiTrieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaiTrieuActionPerformed(evt);
            }
        });

        btnMotTrieu.setText("200.000 VNĐ");
        btnMotTrieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotTrieuActionPerformed(evt);
            }
        });

        btnNamTram.setText("1.000.000 VNĐ");
        btnNamTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamTramActionPerformed(evt);
            }
        });

        btnHaiTram.setText("100.000 VNĐ");
        btnHaiTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaiTramActionPerformed(evt);
            }
        });

        btnMotTram.setText("500.000 VNĐ");
        btnMotTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotTramActionPerformed(evt);
            }
        });

        btnSoKhac.setText("Số khác...");
        btnSoKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoKhacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMotTrieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnMotTram))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNamTram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSoKhac))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHaiTrieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHaiTram, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHaiTram, btnHaiTrieu, btnMotTram, btnMotTrieu, btnNamTram, btnSoKhac});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHaiTrieu)
                    .addComponent(btnHaiTram))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMotTrieu)
                    .addComponent(btnMotTram))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNamTram)
                    .addComponent(btnSoKhac))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHaiTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaiTramActionPerformed
        try {
            if(tt.RutTien(SoTaiKhoan, 200000, "daruttien")) {
                JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thực hiện giao dịch!", "Lỗi giao dịch", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frmRutTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHaiTramActionPerformed

    ITinhToan tt;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            tt = (ITinhToan) Naming.lookup("rmi://localhost:1099/TinhToan");
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMotTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotTramActionPerformed
        try {
            if(tt.RutTien(SoTaiKhoan, 100000, "daruttien")) {
                JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thực hiện giao dịch!", "Lỗi giao dịch", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frmRutTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMotTramActionPerformed

    private void btnNamTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamTramActionPerformed
        try {
            if(tt.RutTien(SoTaiKhoan, 500000, "daruttien")) {
                JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thực hiện giao dịch!", "Lỗi giao dịch", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frmRutTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNamTramActionPerformed

    private void btnMotTrieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotTrieuActionPerformed
        try {
            if(tt.RutTien(SoTaiKhoan, 1000000, "daruttien")) {
                JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thực hiện giao dịch!", "Lỗi giao dịch", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frmRutTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMotTrieuActionPerformed

    private void btnHaiTrieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaiTrieuActionPerformed
        try {
            if(tt.RutTien(SoTaiKhoan, 2000000, "daruttien")) {
                JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thực hiện giao dịch!", "Lỗi giao dịch", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frmRutTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHaiTrieuActionPerformed

    private void btnSoKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoKhacActionPerformed
        new frmRutTienSoKhac(SoTaiKhoan, "daruttien").setVisible(true);
    }//GEN-LAST:event_btnSoKhacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmRutTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHaiTram;
    private javax.swing.JButton btnHaiTrieu;
    private javax.swing.JButton btnMotTram;
    private javax.swing.JButton btnMotTrieu;
    private javax.swing.JButton btnNamTram;
    private javax.swing.JButton btnSoKhac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
